{{- if .Values.services.memcached.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.memcached.name }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "memcached.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      {{- with .Values.services.memcached.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        org.{{ .Chart.Name }}/network: {{ .Release.Name }}-{{ .Release.Namespace }}
        {{- include "memcached.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - memcached
            - $(MEMCACHED_OPTIONS)
          envFrom:
            - secretRef:
                name: {{ include "geonode.name" . }}-memcached
          image: {{ .Values.services.memcached.image.repository }}:{{ .Values.services.memcached.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.services.memcached.image.pullPolicy }}
          name: {{ .Values.services.memcached.name }}
          # livenessProbe:
          #   tcpSocket:
          #     port: memcached
          #   periodSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - '-c'
          #       - echo "quit" | nc 127.0.0.1 11211
          #   periodSeconds: 10
          #   failureThreshold: 3
          securityContext:
            {{- toYaml .Values.services.memcached.securityContext | nindent 12 }}
          ports:
            - name: memcached
              containerPort: 11211
              protocol: TCP
          resources:
            {{- toYaml .Values.services.memcached.resources | nindent 12 }}
      serviceAccountName: {{ include "geonode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.services.memcached.podSecurityContext | nindent 8 }}
      # restartPolicy: Always
      {{- with .Values.services.memcached.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.memcached.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.memcached.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
