apiVersion: v1
kind: Service
metadata:
  name: {{ include "hybras.frontendFullname" . }}
  labels:
    {{- include "hybras.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: frontend-port
      protocol: TCP
      name: frontend-port-svc
  selector:
    {{- include "hybras.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
